name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            echo "GMAIL_API_CLIENT_ID=${{ secrets.GMAIL_API_CLIENT_ID }}" > ~/backend.env
            echo "GMAIL_FROM_EMAIL=${{ secrets.GMAIL_FROM_EMAIL }}" >> ~/backend.env
            echo "GMAIL_API_SECRET=${{ secrets.GMAIL_API_SECRET }}" >> ~/backend.env
            echo "GMAIL_API_REFRESH_TOKEN=${{ secrets.GMAIL_API_REFRESH_TOKEN }}" >> ~/backend.env
            export $(cat ~/backend.env | xargs)
            nohup java -jar ~/libros-0.0.1.jar > ~/backend.log 2>&1 &

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/libros-0.0.1.jar"
          target: "~/"
